modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="the_lotr_mod"
version="1.3.0"
displayName="The LotR Mod"
displayURL="https://mcreator.net/modification/92049/hobbit-mod"
logoFile="logo.png"
credits="gh5674, witherwraith"
authors="gh5674, witherwraith"
description="Introduces the Lord of the Rings into Minecraft."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_lotr_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



